# Generated by Django 6.1.1 on 2026-09-23 09:14

import django.db.models.deletion
from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[apps.common.validators.validar_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razon social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=150, verbose_name='nombre de fantasia')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona natural'), ('juridica', 'Persona juridica')], max_length=10, verbose_name='tipo de persona')),
                ('giro', models.CharField(blank=True, max_length=150, verbose_name='giro')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'db_table': 'comuna',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo oficial')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'db_table': 'region',
                'ordering': ['id_region'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='cargo')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='correo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('principal', models.BooleanField(default=False, verbose_name='es contacto principal')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contacto de cliente',
                'verbose_name_plural': 'contactos de cliente',
                'db_table': 'contacto_cliente',
                'ordering': ['-principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('facturacion', 'Facturacion'), ('despacho', 'Despacho'), ('instalacion', 'Instalacion')], max_length=20, verbose_name='tipo de direccion')),
                ('calle', models.CharField(max_length=200, verbose_name='calle')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('validada', models.BooleanField(default=False, verbose_name='validada por geocodificacion')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente', verbose_name='cliente')),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='clientes.comuna', verbose_name='comuna')),
            ],
            options={
                'verbose_name': 'direccion de cliente',
                'verbose_name_plural': 'direcciones de cliente',
                'db_table': 'direccion_cliente',
                'ordering': ['cliente', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='clientes.region', verbose_name='region'),
        ),
        migrations.AddConstraint(
            model_name='comuna',
            constraint=models.UniqueConstraint(fields=('region', 'nombre'), name='uq_comuna_region_nombre'),
        ),
    ]
