# Generated by Django 6.1.1 on 2026-09-23 09:14

import apps.seguridad.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='codigo')),
                ('modulo', models.CharField(max_length=40, verbose_name='modulo')),
                ('operacion', models.CharField(choices=[('crear', 'Crear'), ('leer', 'Leer'), ('actualizar', 'Actualizar'), ('anular', 'Anular')], max_length=20, verbose_name='operacion')),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permiso',
                'ordering': ['modulo', 'operacion'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='nombre de acceso')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='correo electronico')),
                ('es_interno', models.BooleanField(default=False, verbose_name='es usuario interno')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20, verbose_name='estado')),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos fallidos consecutivos')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='ultimo acceso exitoso')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superusuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='cuenta habilitada')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', help_text='Solo para cuentas web de cliente. Nulo en usuarios internos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='clientes.cliente', verbose_name='cliente asociado')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'ordering': ['username'],
            },
            managers=[
                ('objects', apps.seguridad.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True, verbose_name='asignado en')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='seguridad.rol', verbose_name='rol')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'rol de usuario',
                'verbose_name_plural': 'roles de usuario',
                'db_table': 'usuario_rol',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='seguridad.UsuarioRol', to='seguridad.rol', verbose_name='roles'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=60, verbose_name='entidad afectada')),
                ('id_registro', models.CharField(max_length=40, verbose_name='id del registro')),
                ('accion', models.CharField(choices=[('creacion', 'Creacion'), ('modificacion', 'Modificacion'), ('anulacion', 'Anulacion'), ('acceso_denegado', 'Acceso denegado')], max_length=20, verbose_name='accion')),
                ('valor_anterior', models.JSONField(blank=True, null=True, verbose_name='valor anterior')),
                ('valor_nuevo', models.JSONField(blank=True, null=True, verbose_name='valor nuevo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('origen', models.CharField(blank=True, choices=[('escritorio', 'Aplicacion de escritorio'), ('web', 'Aplicacion web'), ('sistema', 'Proceso automatico')], max_length=40, verbose_name='origen')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'bitacora de auditoria',
                'db_table': 'auditoria',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'entidad', 'fecha_hora'], name='idx_aud_filtro')],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado_en', models.DateTimeField(auto_now_add=True, verbose_name='otorgado en')),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='seguridad.permiso', verbose_name='permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='seguridad.rol', verbose_name='rol')),
            ],
            options={
                'verbose_name': 'permiso de rol',
                'verbose_name_plural': 'permisos de rol',
                'db_table': 'rol_permiso',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso')],
            },
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
    ]
