# Generated by Django 5.1.6 on 2026-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, help_text='Fin del bloqueo temporal por intentos fallidos (RF-SEG-04).', null=True, verbose_name='bloqueado hasta'),
        ),
    ]
