# Generated by Django 6.1.1 on 2026-09-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'familia de producto',
                'verbose_name_plural': 'familias de producto',
                'db_table': 'familia_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroTecnico',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre visible')),
                ('unidad', models.CharField(max_length=20, verbose_name='unidad de medida')),
                ('tipo_dato', models.CharField(choices=[('numerico', 'Numerico'), ('texto', 'Texto'), ('lista', 'Lista de valores')], max_length=20, verbose_name='tipo de dato')),
                ('obligatorio', models.BooleanField(default=True, help_text='Obligatoriedad en el formulario web. Configurable (RF-ADM-04).', verbose_name='obligatorio por defecto')),
            ],
            options={
                'verbose_name': 'parametro tecnico',
                'verbose_name_plural': 'parametros tecnicos',
                'db_table': 'parametro_tecnico',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloProducto',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion tecnica')),
                ('publicado', models.BooleanField(default=False, verbose_name='publicado en el catalogo web')),
                ('familia', models.ForeignKey(db_column='id_familia', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='catalogo.familiaproducto', verbose_name='familia')),
            ],
            options={
                'verbose_name': 'modelo de producto',
                'verbose_name_plural': 'modelos de producto',
                'db_table': 'modelo_producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_defecto', models.CharField(blank=True, max_length=60, verbose_name='valor por defecto')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='obligatorio para este modelo')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='parametros_asignados', to='catalogo.modeloproducto', verbose_name='modelo')),
                ('parametro', models.ForeignKey(db_column='id_parametro', on_delete=django.db.models.deletion.PROTECT, related_name='modelos_asignados', to='catalogo.parametrotecnico', verbose_name='parametro')),
            ],
            options={
                'verbose_name': 'parametro del modelo',
                'verbose_name_plural': 'parametros del modelo',
                'db_table': 'modelo_parametro',
            },
        ),
        migrations.AddField(
            model_name='modeloproducto',
            name='parametros',
            field=models.ManyToManyField(related_name='modelos', through='catalogo.ModeloParametro', to='catalogo.parametrotecnico', verbose_name='parametros tecnicos'),
        ),
        migrations.CreateModel(
            name='PrecioBaseModelo',
            fields=[
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('monto_uf', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='monto en UF')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.modeloproducto', verbose_name='modelo')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'precio base de modelo',
                'verbose_name_plural': 'precios base de modelo',
                'db_table': 'precio_base_modelo',
                'ordering': ['modelo', '-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='TareaEstandarModelo',
            fields=[
                ('id_tarea_estandar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre de la tarea')),
                ('secuencia', models.PositiveSmallIntegerField(verbose_name='secuencia')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='horas hombre estimadas')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_estandar', to='catalogo.modeloproducto', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'tarea estandar del modelo',
                'verbose_name_plural': 'tareas estandar del modelo',
                'db_table': 'tarea_estandar_modelo',
                'ordering': ['modelo', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='ValorParametro',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=60, verbose_name='valor')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentacion')),
                ('parametro', models.ForeignKey(db_column='id_parametro', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.parametrotecnico', verbose_name='parametro')),
            ],
            options={
                'verbose_name': 'valor de parametro',
                'verbose_name_plural': 'valores de parametro',
                'db_table': 'valor_parametro',
                'ordering': ['parametro', 'orden', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='BomModelo',
            fields=[
                ('id_bom', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cantidad por unidad')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='observacion')),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_modelos', to='inventario.material', verbose_name='material')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='catalogo.modeloproducto', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'material del modelo',
                'verbose_name_plural': 'lista de materiales del modelo',
                'db_table': 'bom_modelo',
                'ordering': ['modelo', 'material'],
                'constraints': [models.UniqueConstraint(fields=('modelo', 'material'), name='uq_bom_modelo_material'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_bom_cantidad_positiva')],
            },
        ),
        migrations.AddConstraint(
            model_name='modeloparametro',
            constraint=models.UniqueConstraint(fields=('modelo', 'parametro'), name='uq_modelo_parametro'),
        ),
        migrations.AddConstraint(
            model_name='preciobasemodelo',
            constraint=models.UniqueConstraint(fields=('modelo', 'vigente_desde'), name='uq_precio_modelo_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='preciobasemodelo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_uf__gte', 0)), name='ck_precio_modelo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='tareaestandarmodelo',
            constraint=models.UniqueConstraint(fields=('modelo', 'secuencia'), name='uq_tarea_estandar_secuencia'),
        ),
        migrations.AddConstraint(
            model_name='tareaestandarmodelo',
            constraint=models.CheckConstraint(condition=models.Q(('horas_estimadas__gt', 0)), name='ck_tarea_horas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='valorparametro',
            constraint=models.UniqueConstraint(fields=('parametro', 'valor'), name='uq_valor_parametro'),
        ),
    ]
