# Generated by Django 5.1.6 on 2026-09-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaestandarmodelo',
            name='empleado_sugerido',
            field=models.ForeignKey(blank=True, db_column='id_empleado_sugerido', help_text='Se asigna automaticamente a la tarea al generar la orden de trabajo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_habituales', to='produccion.empleado', verbose_name='responsable habitual'),
        ),
    ]
