# Generated by Django 6.1.1 on 2026-09-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id_feriado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('nombre', models.CharField(max_length=120, verbose_name='denominacion oficial')),
                ('tipo', models.CharField(choices=[('civil', 'Civil'), ('religioso', 'Religioso'), ('regional', 'Regional')], default='civil', max_length=30, verbose_name='tipo')),
                ('obtenido_en', models.DateTimeField(auto_now_add=True, verbose_name='obtenido en')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'db_table': 'feriado',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AvisoSitio',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120, verbose_name='titulo')),
                ('cuerpo', models.TextField(verbose_name='contenido')),
                ('tipo', models.CharField(choices=[('informativo', 'Informativo'), ('advertencia', 'Advertencia'), ('mantencion', 'Mantencion')], default='informativo', max_length=20, verbose_name='tipo')),
                ('vigente_desde', models.DateTimeField(verbose_name='publicar desde')),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True, verbose_name='publicar hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'aviso del sitio',
                'verbose_name_plural': 'avisos del sitio',
                'db_table': 'aviso_sitio',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=40, verbose_name='servicio invocado')),
                ('endpoint', models.CharField(max_length=255, verbose_name='recurso')),
                ('metodo', models.CharField(max_length=10, verbose_name='metodo HTTP')),
                ('codigo_respuesta', models.SmallIntegerField(verbose_name='codigo de estado')),
                ('latencia_ms', models.IntegerField(verbose_name='latencia (ms)')),
                ('exitoso', models.BooleanField(verbose_name='exitoso')),
                ('mensaje_error', models.CharField(blank=True, max_length=500, verbose_name='detalle del error')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
            ],
            options={
                'verbose_name': 'llamada a servicio externo',
                'verbose_name_plural': 'log de integraciones',
                'db_table': 'log_integracion',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['servicio', '-fecha_hora'], name='idx_log_servicio')],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id_parametro_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=60, unique=True, verbose_name='clave')),
                ('valor', models.CharField(max_length=300, verbose_name='valor actual')),
                ('tipo_dato', models.CharField(choices=[('booleano', 'Booleano'), ('numerico', 'Numerico'), ('texto', 'Texto'), ('fecha', 'Fecha')], max_length=20, verbose_name='tipo de dato')),
                ('ambito', models.CharField(choices=[('sistema', 'Sistema'), ('canal_web', 'Canal web'), ('comercial', 'Proceso comercial'), ('produccion', 'Proceso productivo')], max_length=30, verbose_name='ambito')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripcion funcional')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'parametro del sistema',
                'verbose_name_plural': 'parametros del sistema',
                'db_table': 'parametro_sistema',
                'ordering': ['ambito', 'clave'],
            },
        ),
    ]
