# Generated by Django 6.1.1 on 2026-09-23 09:40

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('comercial', '0001_initial'),
        ('inventario', '0002_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[apps.common.validators.validar_rut], verbose_name='RUT')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre completo')),
                ('cargo', models.CharField(max_length=80, verbose_name='cargo')),
                ('usuario', models.OneToOneField(blank=True, db_column='id_usuario', help_text='Solo si el empleado registra directamente en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('id_orden_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numero correlativo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='unidades')),
                ('costo_estimado_uf', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='costo estimado heredado (UF)')),
                ('costo_real_uf', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='costo real acumulado (UF)')),
                ('avance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='avance (%)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='inicio de fabricacion')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='cierre')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='comercial.estadodocumento', verbose_name='estado actual')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='catalogo.modeloproducto', verbose_name='modelo a fabricar')),
                ('orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='comercial.ordencompra', verbose_name='orden de compra de origen')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'ordenes de trabajo',
                'db_table': 'orden_trabajo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoHistorial',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado nuevo')),
                ('orden_trabajo', models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='produccion.ordentrabajo', verbose_name='orden de trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'historial de la orden de trabajo',
                'verbose_name_plural': 'historial de la orden de trabajo',
                'db_table': 'orden_trabajo_historial',
                'ordering': ['-fecha_hora'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TareaOT',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre de la tarea')),
                ('secuencia', models.PositiveSmallIntegerField(verbose_name='secuencia')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='horas hombre estimadas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En ejecucion'), ('terminada', 'Terminada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='fecha estimada')),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to='produccion.empleado', verbose_name='empleado asignado')),
                ('orden_trabajo', models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='produccion.ordentrabajo', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'tarea de la orden de trabajo',
                'verbose_name_plural': 'tareas de la orden de trabajo',
                'db_table': 'tarea_ot',
                'ordering': ['orden_trabajo', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHoraHombre',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha de la jornada')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='horas trabajadas')),
                ('valor_hora_uf', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tarifa congelada (UF/hora)')),
                ('anulado', models.BooleanField(default=False, verbose_name='anulado')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='horas_trabajadas', to='produccion.empleado', verbose_name='empleado')),
                ('usuario_registro', models.ForeignKey(db_column='id_usuario_registro', help_text='Se distingue del empleado: el jefe puede registrar por un ausente.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario que registro')),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.PROTECT, related_name='registros_hora', to='produccion.tareaot', verbose_name='tarea')),
            ],
            options={
                'verbose_name': 'registro de horas hombre',
                'verbose_name_plural': 'registros de horas hombre',
                'db_table': 'registro_hora_hombre',
                'ordering': ['-fecha', '-id_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cantidad consumida')),
                ('costo_unitario_uf', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='costo unitario congelado (UF)')),
                ('planificado', models.BooleanField(default=True, verbose_name='estaba previsto en la lista de materiales')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha del registro')),
                ('bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.bodega', verbose_name='bodega de origen')),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.material', verbose_name='material')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_registrados', to='produccion.empleado', verbose_name='registrado por')),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='produccion.tareaot', verbose_name='tarea')),
            ],
            options={
                'verbose_name': 'consumo de material',
                'verbose_name_plural': 'consumos de material',
                'db_table': 'consumo_material',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TarifaHoraHombre',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('valor_hora_uf', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='valor hora (UF)')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='produccion.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'tarifa de hora hombre',
                'verbose_name_plural': 'tarifas de hora hombre',
                'db_table': 'tarifa_hora_hombre',
                'ordering': ['empleado', '-vigente_desde'],
            },
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_ot_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tareaot',
            constraint=models.UniqueConstraint(fields=('orden_trabajo', 'secuencia'), name='uq_tarea_ot_secuencia'),
        ),
        migrations.AddIndex(
            model_name='registrohorahombre',
            index=models.Index(fields=['tarea', 'empleado'], name='idx_hh_tarea_empleado'),
        ),
        migrations.AddConstraint(
            model_name='registrohorahombre',
            constraint=models.CheckConstraint(condition=models.Q(('horas__gt', 0)), name='ck_horas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='consumomaterial',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_consumo_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tarifahorahombre',
            constraint=models.UniqueConstraint(fields=('empleado', 'vigente_desde'), name='uq_tarifa_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='tarifahorahombre',
            constraint=models.CheckConstraint(condition=models.Q(('valor_hora_uf__gt', 0)), name='ck_tarifa_positiva'),
        ),
    ]
