# Generated by Django 6.1.1 on 2026-09-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id_no_conformidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripcion')),
                ('severidad', models.CharField(choices=[('menor', 'Menor'), ('mayor', 'Mayor'), ('critica', 'Critica')], max_length=20, verbose_name='severidad')),
                ('accion_correctiva', models.TextField(blank=True, verbose_name='accion correctiva')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='estado')),
                ('abierta_en', models.DateTimeField(auto_now_add=True, verbose_name='abierta en')),
                ('cerrada_en', models.DateTimeField(blank=True, null=True, verbose_name='cerrada en')),
            ],
            options={
                'verbose_name': 'no conformidad',
                'verbose_name_plural': 'no conformidades',
                'db_table': 'no_conformidad',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloCalidad',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del protocolo')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='version')),
                ('norma_referencia', models.CharField(blank=True, max_length=80, verbose_name='norma de referencia')),
            ],
            options={
                'verbose_name': 'protocolo de calidad',
                'verbose_name_plural': 'protocolos de calidad',
                'db_table': 'protocolo_calidad',
                'ordering': ['modelo', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del ensayo')),
                ('tipo_ensayo', models.CharField(max_length=60, verbose_name='tipo de ensayo')),
                ('unidad', models.CharField(max_length=20, verbose_name='unidad de medida')),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='valor nominal esperado')),
                ('tolerancia_inf', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='limite inferior admisible')),
                ('tolerancia_sup', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='limite superior admisible')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio, condiciona el cierre de la orden (RN-12).', verbose_name='obligatorio')),
                ('secuencia', models.PositiveSmallIntegerField(verbose_name='secuencia')),
            ],
            options={
                'verbose_name': 'punto de control',
                'verbose_name_plural': 'puntos de control',
                'db_table': 'punto_control',
                'ordering': ['protocolo', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoControl',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('valor_medido', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor medido')),
                ('conforme', models.BooleanField(verbose_name='conforme')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='registrado en')),
            ],
            options={
                'verbose_name': 'resultado de control',
                'verbose_name_plural': 'resultados de control',
                'db_table': 'resultado_control',
                'ordering': ['control', 'punto', '-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('conforme', 'Conforme'), ('con_nc', 'Con no conformidades')], default='en_proceso', max_length=20, verbose_name='estado')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion general')),
                ('inspector', models.ForeignKey(db_column='id_inspector', on_delete=django.db.models.deletion.PROTECT, related_name='controles_ejecutados', to=settings.AUTH_USER_MODEL, verbose_name='inspector responsable')),
            ],
            options={
                'verbose_name': 'control de calidad',
                'verbose_name_plural': 'controles de calidad',
                'db_table': 'control_calidad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
