# Generated by Django 6.1.1 on 2026-09-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='orden_trabajo',
            field=models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad', to='produccion.ordentrabajo', verbose_name='orden de trabajo'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='responsable',
            field=models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='responsable de la accion correctiva'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, db_column='id_usuario_cierre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario que cerro'),
        ),
        migrations.AddField(
            model_name='protocolocalidad',
            name='modelo',
            field=models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='catalogo.modeloproducto', verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='protocolo',
            field=models.ForeignKey(db_column='id_protocolo', on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='calidad.protocolocalidad', verbose_name='protocolo aplicado'),
        ),
        migrations.AddField(
            model_name='puntocontrol',
            name='protocolo',
            field=models.ForeignKey(db_column='id_protocolo', on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='calidad.protocolocalidad', verbose_name='protocolo'),
        ),
        migrations.AddField(
            model_name='resultadocontrol',
            name='control',
            field=models.ForeignKey(db_column='id_control', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='calidad.controlcalidad', verbose_name='control'),
        ),
        migrations.AddField(
            model_name='resultadocontrol',
            name='punto',
            field=models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='calidad.puntocontrol', verbose_name='punto de control'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='resultado',
            field=models.OneToOneField(db_column='id_resultado', on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidad', to='calidad.resultadocontrol', verbose_name='resultado que la origino'),
        ),
        migrations.AddConstraint(
            model_name='protocolocalidad',
            constraint=models.UniqueConstraint(fields=('modelo', 'nombre', 'version'), name='uq_protocolo_version'),
        ),
        migrations.AddConstraint(
            model_name='puntocontrol',
            constraint=models.UniqueConstraint(fields=('protocolo', 'secuencia'), name='uq_punto_control_secuencia'),
        ),
    ]
