# Generated by Django 6.1.1 on 2026-09-23 09:25

import django.db.models.deletion
from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ubicacion', models.CharField(blank=True, max_length=150, verbose_name='ubicacion fisica')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'db_table': 'bodega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoria de material',
                'verbose_name_plural': 'categorias de material',
                'db_table': 'categoria_material',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[apps.common.validators.validar_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=150, verbose_name='razon social')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='correo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('unidad_medida', models.CharField(choices=[('un', 'Unidad'), ('kg', 'Kilogramo'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('l', 'Litro')], max_length=20, verbose_name='unidad de medida')),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=4, help_text='Nivel bajo el cual se emite alerta (RF-INV-06).', max_digits=12, null=True, verbose_name='stock minimo')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.categoriamaterial', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'db_table': 'material',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrecioMaterial',
            fields=[
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('id_precio_material', models.AutoField(primary_key=True, serialize=False)),
                ('costo_uf', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='costo en UF')),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventario.material', verbose_name='material')),
                ('proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precios', to='inventario.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'precio de material',
                'verbose_name_plural': 'precios de material',
                'db_table': 'precio_material',
                'ordering': ['material', '-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('material', 'vigente_desde'), name='uq_precio_material_vigencia'), models.CheckConstraint(condition=models.Q(('costo_uf__gte', 0)), name='ck_precio_material_no_negativo')],
            },
        ),
    ]
