# Generated by Django 6.1.1 on 2026-09-23 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepcion'), ('consumo', 'Consumo productivo'), ('ajuste', 'Ajuste de inventario'), ('devolucion', 'Devolucion')], max_length=20, verbose_name='tipo de movimiento')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Positiva en entradas, negativa en salidas.', max_digits=12, verbose_name='cantidad')),
                ('costo_unitario_uf', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='costo unitario (UF)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.bodega', verbose_name='bodega')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
