# Generated by Django 6.1.1 on 2026-09-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='consumo',
            field=models.OneToOneField(blank=True, db_column='id_consumo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento', to='produccion.consumomaterial', verbose_name='consumo productivo de origen'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='material',
            field=models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.material', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', help_text='Solo en recepciones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['material', 'bodega'], name='idx_mov_material_bodega'),
        ),
    ]
