# Generated by Django 6.1.1 on 2026-09-23 09:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, verbose_name='numero correlativo')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='version')),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor de la UF congelado')),
                ('fecha_valor_uf', models.DateField(verbose_name='fecha del valor de la UF')),
                ('total_uf', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='total en UF')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='descuento aplicado (%)')),
                ('plazo_dias_habiles', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='plazo de fabricacion (dias habiles)')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha comprometida de entrega')),
                ('vence_el', models.DateField(verbose_name='vence el')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente', verbose_name='cliente')),
                ('ejecutivo', models.ForeignKey(db_column='id_ejecutivo', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='ejecutivo responsable')),
            ],
            options={
                'verbose_name': 'cotizacion',
                'verbose_name_plural': 'cotizaciones',
                'db_table': 'cotizacion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionLinea',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='unidades')),
                ('costo_material_uf', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='costo estimado de materiales (UF)')),
                ('costo_hh_uf', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='costo estimado de horas hombre (UF)')),
                ('margen_pct', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=5, verbose_name='margen aplicado (%)')),
                ('precio_uf', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='precio unitario (UF)')),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='comercial.cotizacion', verbose_name='cotizacion')),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cotizadas', to='catalogo.modeloproducto', verbose_name='modelo cotizado')),
            ],
            options={
                'verbose_name': 'linea de cotizacion',
                'verbose_name_plural': 'lineas de cotizacion',
                'db_table': 'cotizacion_linea',
                'ordering': ['cotizacion', 'id_linea'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('solicitud', 'Solicitud de presupuesto'), ('cotizacion', 'Cotizacion'), ('orden_compra', 'Orden de compra'), ('orden_trabajo', 'Orden de trabajo')], max_length=30, verbose_name='tipo de documento')),
                ('codigo', models.CharField(max_length=30, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre visible')),
                ('es_final', models.BooleanField(default=False, verbose_name='cierra el ciclo del documento')),
            ],
            options={
                'verbose_name': 'estado de documento',
                'verbose_name_plural': 'estados de documento',
                'db_table': 'estado_documento',
                'ordering': ['tipo_documento', 'id_estado'],
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'codigo'), name='uq_estado_documento')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionHistorial',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comercial.cotizacion', verbose_name='cotizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado nuevo')),
            ],
            options={
                'verbose_name': 'historial de la cotizacion',
                'verbose_name_plural': 'historial de la cotizacion',
                'db_table': 'cotizacion_historial',
                'ordering': ['-fecha_hora'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='comercial.estadodocumento', verbose_name='estado actual'),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numero correlativo')),
                ('total_uf', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='total en UF')),
                ('anticipo_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='anticipo acordado (%)')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='clientes.cliente', verbose_name='cliente')),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='comercial.cotizacion', verbose_name='cotizacion de origen')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='comercial.estadodocumento', verbose_name='estado actual')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ordenes de compra',
                'db_table': 'orden_compra',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraHistorial',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado nuevo')),
                ('orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comercial.ordencompra', verbose_name='orden de compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'historial de la orden de compra',
                'verbose_name_plural': 'historial de la orden de compra',
                'db_table': 'orden_compra_historial',
                'ordering': ['-fecha_hora'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraLinea',
            fields=[
                ('id_linea_oc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='unidades adquiridas')),
                ('precio_uf', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='precio unitario (UF)')),
                ('cotizacion_linea', models.ForeignKey(db_column='id_cotizacion_linea', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_oc', to='comercial.cotizacionlinea', verbose_name='linea de cotizacion')),
                ('orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='comercial.ordencompra', verbose_name='orden de compra')),
            ],
            options={
                'verbose_name': 'linea de orden de compra',
                'verbose_name_plural': 'lineas de orden de compra',
                'db_table': 'orden_compra_linea',
                'ordering': ['orden_compra', 'id_linea_oc'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numero correlativo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='unidades requeridas')),
                ('fecha_deseada', models.DateField(blank=True, null=True, verbose_name='fecha de entrega deseada')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='clientes.cliente', verbose_name='cliente')),
                ('direccion', models.ForeignKey(blank=True, db_column='id_direccion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='clientes.direccioncliente', verbose_name='direccion de instalacion')),
                ('ejecutivo', models.ForeignKey(blank=True, db_column='id_ejecutivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='ejecutivo asignado')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='comercial.estadodocumento', verbose_name='estado actual')),
                ('modelo', models.ForeignKey(blank=True, db_column='id_modelo', help_text='Nulo si la solicitud no parte de un modelo del catalogo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.modeloproducto', verbose_name='modelo base')),
            ],
            options={
                'verbose_name': 'solicitud de presupuesto',
                'verbose_name_plural': 'solicitudes de presupuesto',
                'db_table': 'solicitud_presupuesto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudHistorial',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observacion')),
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comercial.estadodocumento', verbose_name='estado nuevo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comercial.solicitudpresupuesto', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'historial de la solicitud',
                'verbose_name_plural': 'historial de la solicitud',
                'db_table': 'solicitud_historial',
                'ordering': ['-fecha_hora'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=60, verbose_name='valor declarado')),
                ('parametro', models.ForeignKey(db_column='id_parametro', on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones', to='catalogo.parametrotecnico', verbose_name='parametro tecnico')),
                ('solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='comercial.solicitudpresupuesto', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'especificacion de la solicitud',
                'verbose_name_plural': 'especificaciones de la solicitud',
                'db_table': 'solicitud_especificacion',
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='solicitud',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='comercial.solicitudpresupuesto', verbose_name='solicitud de origen'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionlinea',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_linea_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordencompralinea',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_linea_oc_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuesto',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_solicitud_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='solicitudespecificacion',
            constraint=models.UniqueConstraint(fields=('solicitud', 'parametro'), name='uq_solicitud_parametro'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('numero', 'version'), name='uq_cotizacion_numero_version'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_pct__gte', 0), ('descuento_pct__lte', 100)), name='ck_cotizacion_descuento_rango'),
        ),
    ]
