# Generated by Django 6.1.1 on 2026-09-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCobro',
            fields=[
                ('id_documento_cobro', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='numero correlativo')),
                ('tipo', models.CharField(choices=[('anticipo', 'Anticipo'), ('saldo', 'Saldo')], max_length=20, verbose_name='tipo de cobro')),
                ('monto_uf', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='monto en UF')),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor de la UF aplicado')),
                ('monto_clp', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='monto en pesos (congelado)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('vence_el', models.DateField(verbose_name='vence el')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='emitido en')),
                ('orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cobro', to='comercial.ordencompra', verbose_name='orden de compra')),
            ],
            options={
                'verbose_name': 'documento de cobro',
                'verbose_name_plural': 'documentos de cobro',
                'db_table': 'documento_cobro',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('UF', 'Unidad de Fomento'), ('UTM', 'Unidad Tributaria Mensual'), ('USD', 'Dolar observado')], max_length=10, verbose_name='indicador')),
                ('fecha', models.DateField(verbose_name='fecha del valor')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor')),
                ('obtenido_en', models.DateTimeField(auto_now_add=True, verbose_name='obtenido del servicio en')),
            ],
            options={
                'verbose_name': 'indicador economico',
                'verbose_name_plural': 'indicadores economicos',
                'db_table': 'indicador_economico',
                'ordering': ['-fecha', 'codigo'],
                'indexes': [models.Index(fields=['codigo', '-fecha'], name='idx_indicador_busqueda')],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'fecha'), name='uq_indicador_codigo_fecha'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_indicador_positivo')],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('id_externo', models.CharField(max_length=120, verbose_name='identificador de la pasarela')),
                ('pasarela', models.CharField(max_length=40, verbose_name='pasarela utilizada')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='monto')),
                ('moneda', models.CharField(default='CLP', max_length=3, verbose_name='moneda (ISO 4217)')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('pendiente_conciliacion', 'Pendiente de conciliacion')], default='iniciada', max_length=30, verbose_name='estado')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True, verbose_name='iniciada en')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='resuelta en')),
                ('respuesta', models.JSONField(blank=True, null=True, verbose_name='respuesta completa de la pasarela')),
                ('documento_cobro', models.ForeignKey(db_column='id_documento_cobro', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='pagos.documentocobro', verbose_name='documento de cobro')),
            ],
            options={
                'verbose_name': 'transaccion de pago',
                'verbose_name_plural': 'transacciones de pago',
                'db_table': 'transaccion_pago',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentocobro',
            constraint=models.CheckConstraint(condition=models.Q(('monto_uf__gt', 0)), name='ck_cobro_monto_positivo'),
        ),
    ]
